In [29]:
import numpy as np
import random
import math

class NQueensProblem1D:

    def __init__(self, init_pop_size = 10, no_of_queens = 8, num_epochs = 50, mutation_rate = 0.5):
        self.init_pop_size = init_pop_size
        self.no_of_queens = no_of_queens
        self.population = self.generate_population()
        self.num_epochs = num_epochs
        self.mutation_rate = mutation_rate
        self.best_metric = (self.no_of_queens * (self.no_of_queens - 1)) // 2  # Corrected to integer division
        #self.fitness = self.calculate_fitness()

    def generate_individual(self):
        # Each queen is placed in a random position in a 1D array (no conflicts)
        individual = np.zeros(self.no_of_queens, dtype=int)
        
        for i in range(self.no_of_queens):
            individual[i] = np.random.randint(0, self.no_of_queens)

        return individual

    def generate_population(self):  # generating the first random settings of the queens
        population = []
        for _ in range(self.init_pop_size):
            population.append(self.generate_individual())

        return population

    def mutate_children(self, c):
        ind_length = len(c)
        for j in range(ind_length):  
            if np.random.uniform(0, 1) < self.mutation_rate:
                swap_idx = np.random.randint(0, ind_length)
                c[j], c[swap_idx] = c[swap_idx], c[j]  # Swap mutation

        return c

    def n_crossover(self, p1, p2, n=2):

        split_positions = sorted(np.random.choice(range(self.no_of_queens), n, replace=False))
        c1 = []
        c2 = []
        print("P1: " + str(p1))
        print("P2: " + str(p2))
        subarrays_p1 = np.split(p1, split_positions)
        subarrays_p2 = np.split(p2, split_positions)
        print("subarray P1: " + str(subarrays_p1))
        print("subarray P2: " + str(subarrays_p2))

        for i in range(len(subarrays_p1)):
            if (i % 2 == 0):
                for j in range(len(subarrays_p1[i])):
                    c1.append(subarrays_p1[i][j])
                    c2.append(subarrays_p2[i][j])
            else: 
                for j in range(len(subarrays_p2[i])):
                    c1.append(subarrays_p2[i][j])
                    c2.append(subarrays_p1[i][j])
        print("Child 1 is: " + str(c1))
        print("Child 2 is: " + str(c2))
        return c1,c2


    def fitness_function(self, individual):

        print("individual here is: ", individual)
        n = len(individual)
        individual = np.array(individual)
        total_pairs = n * (n - 1) // 2  # Total possible pairs of queens
        conflicting_pairs = 0

        for i in range(n):
            for j in range(i + 1, n):
                # Check for conflicts
                
                if individual[i] == individual[j]:  # Same column
                    conflicting_pairs += 1
                elif abs(individual[i] - individual[j]) == abs(i - j):  # Same diagonal
                    conflicting_pairs += 1

        non_conflicting_pairs = total_pairs - conflicting_pairs
        return non_conflicting_pairs / total_pairs  # Return the proportion of non-conflicting pairs

    # Uniform Crossover
    def crossover(self, p1, p2):
        crossover_probability = 0.5
        if np.random.uniform(0, 1) < crossover_probability:  # Checks for overall probability 
            for i in range(len(p1)):
                if np.random.uniform(0, 1) < 0.5:  # Genes are swapped with 50% probability
                    p1[i], p2[i] = p2[i], p1[i]  # Swap genes
        return p1, p2

    def run(self):
        best_fitness_per_epoch = []
        print("Running N-Queens Problem: \n")

        fitness_array = []
        
        # Evaluate the fitness of the population
        for i in range(len(self.population)):
            individual = self.population[i]
            #print("Individual here is: ", individual)

            fitness = self.fitness_function(individual)
            fitness_array.append(fitness)

        # Sort individuals based on fitness (ascending order)
        sort_index = [i for i, x in sorted(enumerate(fitness_array), key=lambda x: x[1])]

        # Get the best and second best individuals
        best = sort_index[0]
        second_best = sort_index[1]

        # Perform crossover
        c1, c2 = self.n_crossover(self.population[best], self.population[second_best])

        # Perform mutation
        mutated_c1 = self.mutate_children(c1)
        mutated_c2 = self.mutate_children(c2)

        # Calculate fitness of the mutated children
        fitness_score_mc1 = self.fitness_function(mutated_c1)
        fitness_score_mc2 = self.fitness_function(mutated_c2)
        
        # Replace the worst individuals in the population with the mutated ones
        worst = sort_index[-1]
        second_worst = sort_index[-2]
        self.population[worst] = mutated_c1
        self.population[second_worst] = mutated_c2

        return fitness_score_mc1



In [30]:
nq=  NQueensProblem1D()

nq.run()

Running N-Queens Problem: 

individual here is:  [7 5 1 2 1 1 1 6]
individual here is:  [5 6 0 5 4 1 5 6]
individual here is:  [0 5 0 3 3 1 0 7]
individual here is:  [6 4 7 4 1 0 4 0]
individual here is:  [6 7 4 3 0 6 2 7]
individual here is:  [6 2 5 3 2 1 2 0]
individual here is:  [4 2 1 1 4 0 6 4]
individual here is:  [3 1 1 7 3 0 7 0]
individual here is:  [1 3 6 2 2 4 0 0]
individual here is:  [4 5 3 4 5 2 1 1]
P1: [0 5 0 3 3 1 0 7]
P2: [7 5 1 2 1 1 1 6]
subarray P1: [array([0, 5]), array([0, 3, 3, 1]), array([0, 7])]
subarray P2: [array([7, 5]), array([1, 2, 1, 1]), array([1, 6])]
Child 1 is: [0, 5, 1, 2, 1, 1, 0, 7]
Child 2 is: [7, 5, 0, 3, 3, 1, 1, 6]
individual here is:  [1, 5, 7, 0, 2, 1, 0, 1]
individual here is:  [5, 1, 0, 3, 3, 1, 6, 7]


0.6071428571428571

# Rough Work

In [22]:
def generate_individual():
    no_of_queens = 8
    individual = np.zeros((no_of_queens), dtype=int)
    
    for i in range(no_of_queens):
        individual[i] = np.random.randint(0, no_of_queens)
    print(individual)
    return individual

init_pop_size = 10
def generate_population(init_pop_size): # generating the first random settings of the queens
    population = []
    for _ in range(init_pop_size):
        population.append(generate_individual())
    return population




def fitness_function(individual):
    n = len(individual)
    total_pairs = n * (n - 1) // 2  # Total possible pairs of queens
    conflicting_pairs = 0

    for i in range(n):
        for j in range(i + 1, n):
            # Check for conflicts
            if individual[i] == individual[j]:  # Same column
                conflicting_pairs += 1
            elif abs(individual[i] - individual[j]) == abs(i - j):  # Same diagonal
                conflicting_pairs += 1

    non_conflicting_pairs = total_pairs - conflicting_pairs
    return non_conflicting_pairs / total_pairs  

pop= generate_population(10)
for i in range(len(pop)):
    fitness = fitness_function(pop[i])
    print(fitness)

[4 2 7 2 7 2 7 1]
[2 3 0 3 2 4 7 5]
[1 2 3 7 6 2 0 3]
[0 0 7 2 6 5 2 7]
[5 0 6 6 6 6 3 6]
[4 7 3 1 5 1 4 0]
[2 7 4 7 0 1 4 5]
[2 6 5 1 7 7 5 4]
[7 5 1 6 1 0 5 6]
[5 2 5 5 6 4 6 0]
0.75
0.7142857142857143
0.7142857142857143
0.7142857142857143
0.5714285714285714
0.8214285714285714
0.75
0.7142857142857143
0.75
0.7857142857142857


In [87]:
def mutate(ind):
    print(ind)


np.random.seed(42)
mutation_rate = 0.5
1

c = pop[0]
import numpy as np

# Initialize random seed for reproducibility
np.random.seed(42)

# Example child (permutation)
c = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Mutation parameters
mutation_rate = 0.5  # Probability of mutation


print("Mutated child:", c)

# Print the mutated population
for i in range(len(pop)):
    print(f"Mutated individual {i+1}: {pop[i]}")


Mutated child: [0 1 2 3 4 5 6 7]
Mutated individual 1: [0 2 7 6 7 3 5 7]
Mutated individual 2: [6 6 4 0 7 5 4 5]
Mutated individual 3: [3 6 1 0 1 2 0 7]
Mutated individual 4: [0 7 1 1 7 6 4 6]
Mutated individual 5: [1 0 5 6 4 5 6 1]
Mutated individual 6: [2 6 7 7 0 6 4 1]
Mutated individual 7: [5 1 4 3 6 6 2 6]
Mutated individual 8: [5 1 1 2 2 6 6 0]
Mutated individual 9: [7 3 2 4 4 3 1 2]
Mutated individual 10: [2 6 7 6 1 3 6 6]


In [ ]:

### Implement roulette selection
def roulette:
    pass

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=39a91287-2189-48c9-99b5-0dfcdbf377a7' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>