In [6]:
import numpy as np

binary_sequence = np.random.choice([0, 1], size=10)
print(binary_sequence)

[0 1 1 0 0 1 1 0 1 0]


In [41]:
signed_sequence = binary_sequence * 2 - 1
print(signed_sequence)

[-1 -1  1 -1 -1  1 -1  1 -1  1]


In [81]:
class LABS:
    def __init__(self, length = 4, init_pop_size = 1):
        #self.length_string = length_string
        self.length = length
        self.init_pop_size = init_pop_size
        self.binary_sequence = None 
        self.signed_sequence = None
        self.mutation_rate = 0.5
        self.population = []
        self.signed_population = []
        self.child = None
        self.LABS_scores = []


        '''
    def generate_population(self):
        for i in range(self.imit_pop_size):
            self.population.append(self.generate_binary())

        for i in range(len(self.population)):
            self.signed_population[i].append(self.generate_signed())
    '''

    def generate_binary(self):
        self.binary_sequence = np.random.choice([0, 1], size=self.length)
        self.population.append(self.binary_sequence)

    def generate_signed(self):
        self.signed_sequence = self.binary_sequence * 2 - 1
        print(self.signed_sequence)
        #return signed_sequence

    def calculate_rk(self, k):
        n = self.length
        r_k = 0
        if (k < n):
            for i in range( n - k):
                r_k += self.signed_sequence[i] * self.signed_sequence[i+k]
        else:
            print("Index out of range")
        return r_k
    
    def calculate_autocorrelation(self):
        autocorr_score = 0
        n = self.length
        for k in range(1, n):
            autocorr_score += (self.calculate_rk(k))**2
        return autocorr_score

    def calculate_LABS(self):
        LABS_score = self.length**2/ (2 * self.calculate_autocorrelation())
        self.LABS_scores.append(LABS_score)
        return LABS_score


    def mutate(self):
        temp = self.binary_sequence.copy()  # Make a copy of the sequence
        children = []
        for _ in range(self.length):  # Loop to generate multiple children
            child = temp.copy()  # Make a copy of the sequence for each child
            for i in range(self.length): 
                if np.random.rand() < self.mutation_rate:
                    child[i] = 1 - child[i]  # Flip the bit (mutate)
            children.append(child)  # Append the mutated child to the list
        return children




    def run(self):
        print("Generate population: \n")
        self.generate_population()
        print("Calculate LABS score: \n")

        #self.generate_binary()
        #self.generate_signed()
        #self.calculate_LABS()
        #child = self.mutate()


In [87]:
lab_instance = LABS(length = 4)
lab_instance.generate_binary()
lab_instance.generate_signed()
lab_score =lab_instance.calculate_LABS()
print(lab_score)
children = lab_instance.mutate()
print(children)

labs_scores_children = []

for i in range(len(children)):
    lab_instance.binary_sequence = children[i]
    lab_instance.generate_signed()
    labs_score = lab_instance.calculate_LABS()
    print("Labs score: ",labs_score)
    labs_scores_children.append(labs_score)


#labs_scores_children.sort(reverse = True)
#print(labs_scores_children)
max_score = max(labs_scores_children)

# Step 2: Get all indices where the score is equal to the max score
indices_of_best_children = [i for i, score in enumerate(labs_scores_children) if score == max_score]

print("Indices of best children:", indices_of_best_children)
for i in range(len(indices_of_best_children)):
    lab_instance.population.append(children[i])

[ 1 -1  1 -1]
0.5714285714285714
[array([1, 0, 1, 0]), array([0, 0, 0, 1]), array([0, 1, 0, 0]), array([1, 0, 1, 0])]
[ 1 -1  1 -1]
Labs score:  0.5714285714285714
[-1 -1 -1  1]
Labs score:  4.0
[-1  1 -1 -1]
Labs score:  4.0
[ 1 -1  1 -1]
Labs score:  0.5714285714285714
Indices of best children: [1, 2]


In [34]:
import numpy as np

def binary_to_signed(binary_sequence):
    """
    Convert binary sequence (0, 1) to signed sequence (-1, 1).
    s_i = 2 * x_i - 1
    """
    return 2 * np.array(binary_sequence) - 1

def calculate_autocorrelation(signed_sequence):
    """
    Calculate the autocorrelation sum for a given signed sequence.
    """
    n = len(signed_sequence)
    autocorrelation_sum = 0

    # Iterate over all possible shifts k
    for k in range(1, n):  # k starts from 1 (non-zero shifts)
        autocorrelation_k = 0
        for i in range(n - k):  # Compute autocorrelation for shift k
            autocorrelation_k += signed_sequence[i] * signed_sequence[i + k]
        autocorrelation_sum += autocorrelation_k ** 2  # Square and accumulate

    return autocorrelation_sum

def labs_objective(binary_sequence):
    """
    Compute the LABS objective value for a binary sequence.
    """
    n = len(binary_sequence)
    signed_sequence = binary_to_signed(binary_sequence)
    autocorrelation_sum = calculate_autocorrelation(signed_sequence)

    # LABS formula
    labs_score = n ** 2 / (2 * autocorrelation_sum)
    return labs_score

# Example usage
binary_sequence = [0, 0, 0, 1]
print("Binary sequence:", binary_sequence)
labs_score = labs_objective(binary_sequence)
print("LABS score:", labs_score)




Binary sequence: [0, 0, 0, 1]
LABS score: 4.0


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=39a91287-2189-48c9-99b5-0dfcdbf377a7' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>